{"uuid":"b6eae392-863a-4e5a-8e6e-c9de7eb4c4f5","historyId":"254e4f134afac7fbd816bd0c3aba4e23","fullName":"com.testNGPract.DemoTest.testDivideByZeroException","labels":[{"name":"package","value":"com.testNGPract.DemoTest"},{"name":"testClass","value":"com.testNGPract.DemoTest"},{"name":"testMethod","value":"testDivideByZeroException"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"SeleniumPractice"},{"name":"subSuite","value":"com.testNGPract.DemoTest"},{"name":"host","value":"Namma-MacBook-Air.local"},{"name":"thread","value":"8778@Namma-MacBook-Air.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"testDivideByZeroException","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\nExpected exception of type class java.io.IOException but got java.lang.ArithmeticException: / by zero","trace":"org.testng.TestException: \nExpected exception of type class java.io.IOException but got java.lang.ArithmeticException: / by zero\n\tat org.testng.internal.invokers.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:67)\n\tat org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:853)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:718)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:819)\n\tat org.testng.TestRunner.run(TestRunner.java:619)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\n\tat org.testng.TestNG.run(TestNG.java:1101)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\nCaused by: java.lang.ArithmeticException: / by zero\n\tat com.testNGPract.DemoTest.testDivideByZeroException(DemoTest.java:30)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\n\t... 21 more\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1707644790906,"stop":1707644790910}